app/routes.py
from collections import defaultdict
import os
from queue import Empty, Queue
from threading import Lock, Thread
import traceback
from flask import Blueprint, json, logging, render_template, session, url_for, flash, redirect, request , jsonify ,current_app ,Response
import pandas as pd
from flask_login import login_user, current_user, logout_user, login_required

from app import  bcrypt, create_app
from app.forms import MomryaForm, RegistrationForm, LoginForm, EmployeeForm , HolidayForm, UserForm , UserSettingsForm , JobScheduleOverrideForm , AgazaForm ,AltmasForm ,ClinicForm ,EznForm
from app.models import Appear, EmployeeRates, Momrya, User, Employee, Attendance , OfficialHoliday  ,JobScheduleOverride , Ezn , Clinic , Agaza , Altmas , Approvals , Deduction as DED, Permission
from sqlalchemy.exc import IntegrityError
from sqlalchemy import case, func , String , and_, or_
from datetime import datetime, timedelta, timezone , time
from werkzeug.security import generate_password_hash 
from app.helpers import calculate_agaza_duration_this_year, convert_to_arabic_numerals, days_between_dates, format_date_to_arabic, format_time_to_arabic, generate_mo2srat_report, get_absent_employees, get_user_name_by_office, handle_attendance_reports , get_user_office_and_type , generate_attendance_report , manage_agaza
from app.extensions import db
from werkzeug.utils import secure_filename
from sqlalchemy.orm import aliased
from sqlalchemy.orm import Session
from app.Face_Recognition.scripts.frame_generator import generate_frames
from sqlalchemy.exc import NoResultFound
import time as time_module
from sqlalchemy import case, func , String , and_, or_ , exc
from sqlalchemy import text
from app.utils import permission_required

main = Blueprint('main', __name__)



event_queue = Queue()

@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    #print("Form Loaded")  # Debug #print

    if form.validate_on_submit():
        #print("Form Validated")  # Debug #print

        # Check if the username already exists
        existing_user = User.query.filter_by(username=form.username.data).first()
        if existing_user:
            flash('اسم المستخدم موجود بالفعل. الرجاء اختيار اسم مستخدم مختلف.', 'danger')
            #print("Username already exists")  # Debug #print
            return render_template('register.html', title='Register', form=form)

        # Check if the email already exists
        existing_email = User.query.filter_by(email=form.email.data).first()
        if existing_email:
            flash('البريد الإلكتروني موجود بالفعل. الرجاء اختيار بريد إلكتروني مختلف.', 'danger')
            #print("Email already exists")  # Debug #print
            return render_template('register.html', title='Register', form=form)

        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password_hash=hashed_password, user_type='user')
        
        try:
            #print("Attempting to add user to DB")  # Debug #print
            db.session.add(user)
            db.session.commit()
            #print("User added to DB successfully")  # Debug #print

            flash('تم إنشاء حسابك! أنت الآن قادر على تسجيل الدخول', 'success')
            return redirect(url_for('main.login'))
        except Exception as e:
            #print("Error while adding user to DB")  # Debug #print
            db.session.rollback()
            flash('حدث خطأ أثناء إنشاء حسابك. يرجى المحاولة مرة أخرى في وقت لاحق.', 'danger')
            #print(str(e))  # Debug #print to show the exception

    else:
        #print("Form not validated")  # Debug #print
        for field, errors in form.errors.items():
            for error in errors:
                print(f"Error in the {field} field - {error}")  # Print form errors

    return render_template('register.html', title='Register', form=form)

@main.route('/', methods=['GET', 'POST'])
@main.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        if current_user.user_type == 'admin':
            return redirect(url_for('main.admin_dashboard'))
        else:
            return redirect(url_for('main.admin_dashboard'))
    
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password_hash, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')

            return redirect(next_page) if next_page else redirect(url_for('main.admin_dashboard'))

        else:
            flash('تسجيل الدخول غير ناجح. يرجى التحقق من البريد الإلكتروني وكلمة المرور', 'danger')
    return render_template('login.html', title='Login', form=form)

@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.login'))

@main.route('/admin_dashboard')
@login_required
@permission_required('read')
def admin_dashboard():
    print("current_user current_user" , current_user)
    today = datetime.today().date()

    # Calculate the first day of the current month
    date_from = today.replace(day=1)

    # Calculate date_to as today or the end of the month
    date_to = today  
    #print('date_from' , date_from)
    #print('date_to' , date_to)
    # Fetch the user's office and user_type
    user_info = get_user_office_and_type(current_user.id)
    user_office = user_info.get('office')
    user_type = user_info.get('user_type')

    # Initialize variables to hold the report data
    check_in_attendance = []
    check_out_attendance = []
    check_in_delays = []
    check_out_ahead = []
    clinic = []
    ezn = []
    agaza = []
    altmas = []
    data={}
    points={}
    #print("user_type" ,user_type )
    #print("user_office", user_office)
    #print('current_user.id' , current_user.id)
    # If the user is a manager, fetch data only for their office
    if user_type == 'manager':
        check_in_attendance = handle_attendance_reports(report_type='check_in_attendance', report_date=today, employee_office_name=user_office)
        check_out_attendance = handle_attendance_reports(report_type='check_out_attendance', report_date=today, employee_office_name=user_office)
        check_in_delays = handle_attendance_reports(report_type='check_in_delays', report_date=today, include_delay_minutes=True, employee_office_name=user_office)
        check_out_ahead = handle_attendance_reports(report_type='check_out_ahead', report_date=today, include_leave_early_time=True, employee_office_name=user_office)
        clinic = handle_attendance_reports(report_type='clinic', report_date=today, employee_office_name=user_office)
        ezn = handle_attendance_reports(report_type='ezn', report_date=today, employee_office_name=user_office)
        agaza = handle_attendance_reports(report_type='agaza', report_date=today, employee_office_name=user_office)
        altmas = handle_attendance_reports(report_type='altmas', report_date=today, employee_office_name=user_office)
        rest = handle_attendance_reports(report_type='rest', report_date=today, employee_office_name=user_office)
        data = {
        'check_in_attendance': len(check_in_attendance),
        'check_out_attendance': len(check_out_attendance),
        'check_in_delays': len(check_in_delays) - 1 if len(check_in_delays) > 0 else 0,
        'check_out_ahead': len(check_out_ahead) - 1 if len(check_out_ahead) > 0 else 0,
        'clinic': len(clinic),
        'ezn': len(ezn),
        'agaza': len(agaza),
        'altmas': len(altmas),
        'rest': len(rest)
         }
    
    elif user_type == 'employee':
        employee = Employee.query.filter_by(id=current_user.id).first_or_404()
        points={
        'tar7eel_points': employee.tar7eel_points,
        'sanwya_points': employee.sanwya_points,
        'arda_points': employee.arda_points
        }
        check_in_attendance = handle_attendance_reports(report_type='check_in_attendance', date_from=date_from, date_to=date_to, id=current_user.id)
        check_out_attendance = handle_attendance_reports(report_type='check_out_attendance', date_from=date_from, date_to=date_to, id=current_user.id)
        check_in_delays = handle_attendance_reports(report_type='check_in_delays', date_from=date_from, date_to=date_to, include_delay_minutes=True, id=current_user.id)
        check_out_ahead = handle_attendance_reports(report_type='check_out_ahead', date_from=date_from, date_to=date_to, include_leave_early_time=True, id=current_user.id)
        clinic = handle_attendance_reports(report_type='clinic', date_from=date_from, date_to=date_to, id=current_user.id)
        ezn = handle_attendance_reports(report_type='ezn', date_from=date_from, date_to=date_to, id=current_user.id)
        agaza = handle_attendance_reports(report_type='agaza', date_from=date_from, date_to=date_to, id=current_user.id)
        altmas = handle_attendance_reports(report_type='altmas', date_from=date_from, date_to=date_to, id=current_user.id)
        absent = get_absent_employees( date_from=date_from, date_to=date_to, employee_id=current_user.id)
        data = {
        'check_in_attendance': len(check_in_attendance),
        'check_out_attendance': len(check_out_attendance),
        'check_in_delays': len(check_in_delays) - 1 if len(check_in_delays) > 0 else 0,
        'check_out_ahead': len(check_out_ahead) - 1 if len(check_out_ahead) > 0 else 0,
        'clinic': len(clinic),
        'ezn': len(ezn),
        'agaza': len(agaza),
        'altmas': len(altmas),
        'absent': len(absent)
         }
    else:
        # Fetch data for all employees if the user is not a manager
        check_in_attendance = handle_attendance_reports(report_type='check_in_attendance', report_date=today , period='الفترة الصباحية')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicon -->
    <link rel="icon" href="{{ url_for('static', filename='images/logo.png') }}" type="image/x-icon">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/all.min.css') }}">
        <script src="{{ url_for('static', filename='js/jquery-3.5.1.slim.min.js') }}"></script>
    <style>
   /* Navbar styling */
/* Navbar transition and brand image hover effect */
.navbar {
    font-weight: 400;
    transition: background 0.25s ease;
    -webkit-transition: background 0.25s ease;
    -moz-transition: background 0.25s ease;
    -ms-transition: background 0.25s ease;
    -webkit-box-shadow: 0px 5px 21px -5px #CDD1E1;
    -moz-box-shadow: 0px 5px 21px -5px #CDD1E1;
    box-shadow: 0px 5px 21px -5px #CDD1E1;
    background-color: #ffffff; /* White background for navbar */
    position: fixed;
    width: -webkit-fill-available;
    z-index: 5;
}

/* Navbar brand image transition */
.navbar-brand img {
    transition: transform 0.3s ease;
}

.navbar-brand img:hover {
    transform: scale(1.1);
}

/* Navbar link color and hover effect */
.navbar-dark .navbar-nav .nav-link {
    color: #7978e9; /* Primary color for links */
    transition: color 0.3s;
}

.navbar-dark .navbar-nav .nav-link:hover {
    color: #4b49ac; /* Hover color */
}

/* Dropdown menu styling */
.dropdown-menu {
    min-width: 150px;
}

.dropdown-item img {
    width: 20px;
    height: 14px;
    margin-right: 10px;
}

.dropdown-item {
    display: flex;
    align-items: center;
}

.dropdown-item:hover {
    background-color: #7da0fa; /* Supporting color for hover */
}

/* Clock styling */
#clock {
    color: #ffffff; /* White color for the clock text */
    font-size: 1rem;
    background-color: #7da0fa; /* Supporting color for the clock background */
    margin-top: 10px;
    padding-top: 10px; /* Add padding for better appearance */
    padding-bottom: 10px;
    border-radius: 5px; /* Rounded corners for a softer look */
    box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1); /* Subtle shadow for better visibility */
}

/* Language dropdown styling */
.language-dropdown .dropdown-toggle::after {
    display: none;
}

.language-dropdown {
    position: relative;
}

.language-dropdown img {
    width: 24px;
    height: 16px;
}
/* Navbar link styling */
 .navbar-nav .nav-link {
    color: #7978e9; /* Primary color for links */
    font-weight: 500; /* Font weight for links */
    position: relative; /* Required for positioning the underline */
    transition: color 0.3s, font-weight 0.3s; /* Smooth transition */
    margin-right: 30px;
}

/* Navbar link hover effect */
 .navbar-nav .nav-link:hover {
    color: #4b49ac; /* Hover color */
}

 .navbar-nav .nav-link::after {
    content: ""; /* No text, just an underline */
    position: absolute; /* Positioned relative to the link */
    left: 0;
    bottom: -5px; /* Adjust as needed for spacing */
    width: 100%;
    height: 5px; /* Thickness of the underline */
    background-color: #4b49ac; /* Primary color for the underline */
    transition: width 0.3s; /* Smooth transition */
    transform: scaleX(0); /* Initially hidden */
    transform-origin: bottom right; /* Position of the transform */
}

 .navbar-nav .nav-link:hover::after {
    transform: scaleX(1); /* Show underline on hover */
    transform-origin: bottom left; /* Animate from left to right */
}
#clock::after{
    content: ""; /* No text, just an underline */
    position: absolute; /* Positioned relative to the link */
    left: 0;
    bottom: -5px; /* Adjust as needed for spacing */
    width: 100%;
    height: 0px !important; /* Thickness of the underline */
    color: #ffffff !important; /* Hover color */

    background-color: #ffffff !important; /* Primary color for the underline */
    transition: width 0.3s; /* Smooth transition */
    transform: scaleX(0); /* Initially hidden */
    transform-origin: bottom right; /* Position of the transform */
}


    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg ">
        <a class="navbar-brand" style="margin-left: 50px;" href="{{ url_for('main.admin_dashboard') }}">
            <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Modli Logo" height="50">
        </a>

        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown language-dropdown" style=" padding-top: 10px; ">
                    <a class="nav-link dropdown-toggle" href="#" id="languageDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img id="languageFlag" src="/static/images/egypt_flag.png" alt="Language Flag"> 
                        <span id="languageText">العربية</span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="languageDropdown">
                        <a class="dropdown-item" href="#" onclick="setLanguage('ar')">
                            <img src="/static/images/egypt_flag.png" alt="Arabic Flag"> العربية
                        </a>

                    </div>
                </li>
                
                <li class="nav-item" id="coc">
                    <span id="clock" class="nav-link"></span>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" style=" padding-top: 20px; " href="{{ url_for('main.admin_dashboard') }}">القائمة الرئيسية</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style=" padding-top: 20px; " href="{{ url_for('main.logout') }}">تسجيل خروج</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" style=" padding-top: 20px; " href="{{ url_for('main.login') }}">تسجيل دخول</a>
                </li>

                {% endif %}
            </ul>
        </div>
    </nav>

    {% block content %}{% endblock %}

    <!-- Bootstrap JS and dependencies -->
    <script src="{{ url_for('static', filename='js/jquery-3.5.1.slim.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script>
        function setLanguage(lang) {
            // Save the language preference in sessionStorage
            sessionStorage.setItem('language', lang);
    
            // Reload the page to reflect the language change
            location.reload();
        }
    
        function applyStoredLanguage() {
            const language = sessionStorage.getItem('language');
            const flagImage = document.getElementById('languageFlag');
            const languageText = document.getElementById('languageText');
    
            if (language) {
                if (language === 'ar') {
                    flagImage.src = '/static/images/egypt_flag.png';
                    languageText.textContent = 'العربية';
                } 
            }
        }
    
        // Apply the stored language when the page loads
        document.addEventListener('DOMContentLoaded', applyStoredLanguage);
    
        function updateClock() {
            var now = new Date();
            var hours = now.getHours().toString().padStart(2, '0');
            var minutes = now.getMinutes().toString().padStart(2, '0');
            var seconds = now.getSeconds().toString().padStart(2, '0');
            var day = now.getDate().toString().padStart(2, '0');
            var month = (now.getMonth() + 1).toString().padStart(2, '0'); // Months are zero-based
            var year = now.getFullYear();
            var timeString = hours + ':' + minutes + ':' + seconds;
            var dateString = day + '/' + month + '/' + year;
            document.getElementById('clock').innerHTML = dateString + ' ' + timeString;
        }
        setInterval(updateClock, 1000);
        updateClock();
    </script>
    
</body>
</html>

app/templates/login.html
{% extends "base.html" %}
{% block title %}تسجيل الدخول{% endblock %}

{% block content %}
<style>


    .container {
        max-width: 400px;
        margin-top: 5%;
        margin-left: 75%;
    }
    body {
        background-image: url("{{ url_for('static', filename='background.jpg') }}");
         background-size: cover; 
         background-position: center; 
         background-repeat: no-repeat;

    }

    .card {
        background-color: rgba(255, 255, 255, 0.8);
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .card-header h2 {
        text-align: center;
        margin-bottom: 20px;
        color: #333;
    }

    .form-group label {
        color: #555;
    }

    .form-control {
        border-radius: 5px;
    }

    .btn-primary {
        width: 100%;
        background-color: #007bff;
        border-color: #007bff;
        border-radius: 5px;
        padding: 10px;
    }

    .btn-primary:hover {
        background-color: #0056b3;
        border-color: #0056b3;
    }
</style>

<div class="container">
        <!-- Flash message section -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="alert-container">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
<div class="card">
    <div class="card-header">
        <h2>تسجيل الدخول</h2>
    </div>
    <div class="card-body">
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control") }}
                {% for error in form.email.errors %}
                <small class="form-text text-danger">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control") }}
                {% for error in form.password.errors %}
                <small class="form-text text-danger">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="form-group form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
            <button type="submit" class="btn btn-primary">تسجيل الدخول</button>
        </form>
    </div>
</div>


{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% block title %}انشاء حساب{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h2>انشاء حساب</h2>
    </div>
    <div class="card-body">
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control") }}
                {% for error in form.username.errors %}
                <small class="form-text text-danger">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control") }}
                {% for error in form.email.errors %}
                <small class="form-text text-danger">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control") }}
                {% for error in form.password.errors %}
                <small class="form-text text-danger">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {{ form.confirm_password(class="form-control") }}
                {% for error in form.confirm_password.errors %}
                <small class="form-text text-danger">{{ error }}</small>
                {% endfor %}
            </div>
            <button type="submit" class="btn btn-primary">انشاء حساب</button>
        </form>
    </div>
</div>
{% endblock %}